--- 
abstract: CRUD interface to Hatena::Diary
author: 
  - Tokuhiro Matsuno <tokuhirom gmail com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: WWW-HatenaDiary
no_index: 
  directory: 
    - inc
    - t
requires: 
  JSON::Syck: 0
  URI: 0
  WWW::HatenaLogin: 0.02
  WWW::Mechanize: 0
  Web::Scraper: 0
version: 0.02
